#!/bin/sh

# A script to uninstall SoftMaker Office.

clear
echo ""
echo "This script will remove SoftMaker FreeOffice."
echo ""
echo -n "Do you want to continue (y/n)? [n] " 
read inp
if [ "$inp" != "y" ]
then
  echo "Installation aborted." 
  echo "Press Return to close."
  read inp
  exit
fi


rm -f /home/abay/textmakerfree
rm -f /home/abay/planmakerfree
rm -f /home/abay/presentationsfree
echo Removing document icons...
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-tmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-pmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-prlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-tmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-pmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-prd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-tmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-pmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-prv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 48 application-x-prs
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-tmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-pmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-pmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-tmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-pmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-pmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-tmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-pmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-prv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 32 application-x-prs
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-tmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-pmlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-prlfree
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-tmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-pmd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-prd
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-tmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-pmv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-prv
sh /usr/bin/xdg-icon-resource uninstall --novendor --mode  user  --size 16 application-x-prs
echo Unregistering MIME types...
sh /usr/bin/xdg-mime uninstall  --mode user  --novendor /home/abay/freeoffice/mime/softmaker-freeoffice.xml
echo Removing icons from the menu...
sh /usr/bin/xdg-desktop-menu uninstall --noupdate --novendor --mode  user  /home/abay/freeoffice/mime/textmaker-free.desktop
sh /usr/bin/xdg-desktop-menu uninstall --noupdate --novendor --mode  user  /home/abay/freeoffice/mime/planmaker-free.desktop
sh /usr/bin/xdg-desktop-menu uninstall --noupdate --novendor --mode  user  /home/abay/freeoffice/mime/presentations-free.desktop
sh /usr/bin/xdg-desktop-menu forceupdate --mode  user 
echo Removing icons from the desktop...
sh /usr/bin/xdg-desktop-icon uninstall --novendor  /home/abay/freeoffice/mime/textmaker-free.desktop
sh /usr/bin/xdg-desktop-icon uninstall --novendor  /home/abay/freeoffice/mime/planmaker-free.desktop
sh /usr/bin/xdg-desktop-icon uninstall --novendor  /home/abay/freeoffice/mime/presentations-free.desktop
update-mime-database /usr/share/mime >/dev/null 2>&1
update-desktop-database /usr/share/applications >/dev/null 2>&1
update-desktop-database /usr/share/mimelnk/application >/dev/null 2>&1
echo Removing /home/abay/freeoffice
rm -f -r /home/abay/freeoffice
echo Uninstall complete.
sleep 1 && rm -f /home/abay/uninstallfreeoffice
